<style>
main {
    display: flex;
    flex-direction: column;
}
.filtre {
    order: 1;
    padding: 30px;
}
.content {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    padding: 30px;
    order: 2;
}
.post {
    display: flex;
    flex-direction: row;
    margin: 1em 0;
    background: #eee;
    width: 700px;
}
.post-image {
    width: 150px;
    height: 100%;
    object-fit: cover;
    margin-right: 1em;
}
.post-info {
    display: flex;
    flex-direction: column;
}
.post-title {
    font-size: 1.2em;
    font-weight: bold;
    margin-bottom: 0.5em;
}
.post-author {
    font-style: italic;
    margin-bottom: 0.5em;
}
.post-date {
    font-style: italic;
    margin-bottom: 0.5em;
}
.post-content {
    margin-bottom: 0.5em;
}
.post-num-comments {
    font-style: italic;
}
</style>

<!-- Affichage des articles de blog -->
<div class="content">
    <?php foreach ($posts as $post): ?>
        <div class="post">
            <img class="post-image" src="<?= $post->image_url ?>" alt="<?= $post->title ?>">
            <div class="post-info">
                <h2 class="post-title"><?= $post->title ?></h2>
                <p class="post-author">Par <?= $post->author ?></p>
                <p class="post-date"><?= $post->date ?></p>
                <p class="post-content"><?= $post->content ?></p>
                <p class="post-num-comments"><?= $post->num_comments ?> commentaire(s)</p>
                <p><a href="./index.php?route=comments&post_id=<?= $post->id ?>">Voir les commentaires</a></p>
            </div>      
        </div>
    <?php endforeach; ?>
</div>


<!-- Affichage du filtre -->
<div class="filtre">
    <?php $posts = Post::getAll(); ?>

    <form id="filter-form" action="./Controller/postsfilter.php" method="post">
        <label for="user_name">Filtres :</label>
        <select name="user_name" id="user_name">
            <option value="">Please select an author</option>
            <?php
                $authors = [];
                foreach ($posts as $post): 
                    if (!in_array($post->author, $authors)) {
                        $authors[] = $post->author;
                        echo "<option value='$post->author'>$post->author</option>";
                    }
                endforeach;
                ?>
        </select>
        <input type="submit" value="Rechercher" onclick="verifFilter()">
    </form>
</div>

<script>
  function verifFilter() {
    let select = document.getElementById("user_name").value;

    if (select == "") {
        alert("Sélectionnez un auteur !");
        return;
    }

    document.getElementById("filter-form").submit();
  }

  document.getElementById("filter-form").addEventListener("submit", () => {
    if (event.preventDefault) event.preventDefault();
    else event.returnValue = false;
  });
</script>