<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Comments</title>
</head>
<body>
<?php include('./View/header.php'); ?>

    <h1>Comments</h1>
    <p>All comments<p>
    <?php foreach($comments as $comment): ?>
	<?php echo $comment->id.'<br>'?>
	<?php  echo $comment->title.'<br>'?>
	<?php  echo $comment->body.'<br>'?>
    <?php endforeach; ?>
</body>
</html>