<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
<?php include('./View/header.php'); ?>

    <h1>Home</h1>
    <p>All posts<p>
    <?php foreach($posts as $post): ?>
	<?php  echo $post->title.'<br>'?>
	<?php  echo $post->body.'<br>'?>

    <?php endforeach; ?>
</body>
</html>