<style>

main {
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 30px;    
}
h2 {
    background: pink;
    font-size: 30px;
}
.div1 {
    background: salmon;
    width: 100%;
    height: 50vh;
    position: relative;
}
.div1 h3,
.div2 h3 {
    font-size: 24px;
}
.div1 span {
    font-size: 54px;
    background: cyan;
    color: maroon;
    position: absolute;
    bottom: 10px;
    right: 10px;
}
.div2 {
    margin-top: 50px;
    display: flex;
    flex-direction: column;
    /* align-items: center; */
}
.div2 span:nth-child(odd) {
    margin-bottom: 20px;
}
</style>

<!-- Affichage de la page d'accueil -->
<h2>Voici notre magnifique Blog</h2>

<div class="div1">
    <h3>Blog créé dans le cadre d'un projet PHP</h3>
    <span>Où le design CSS est extêmement important !</span>
</div>

<div class="div2">
    <h3>Liste des query possible d'utilisation :</h3>

    <span>Accueil du site</span>
    <span>route=home</span>
    
    <span>Liste de tous les articles</span>
    <span>route=posts</span>
    
    <span>Liste de tous les articles de blog d'un utilisateur d'après le nom</span>
    <span>route=user_posts&user_name={nom (exemple: Charlie)}</span>

    <span>Affiche un article de blog d'après l'ID</span>
    <span>route=post&post_id={ID de l'article (exemple: 2)}</span>

    <span>Liste de tous les commentaires d'un article de blog d'après l'ID</span>
    <span>route=comments&post_id={ID de l'article (exemple: 2)}</span>

    <span>Affiche un commentaire de blog d'après l'ID</span>
    <span>route=comment&comment_id={ID du commentaire (exemple: 2)}</span>

    <span>Page d'ajout d'article</span>
    <span>route=new_post</span>

    <span>Page d'ajout d'un commentaire à un article</span>
    <span>route=newcomment&post_id={ID du commentaire (exemple: 2)}</span>

    <span>Page 404 si query ne correspon à rien</span>
    <span>route={autre valeur (exemple: lorem)}</span>

</div>
