<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Orders</title>
</head>
<body>
<h1>page orders</h1>
<?php include('header.php'); ?>

    <h1>orders</h1>
    <p>All orders<p>
    <?php foreach($orders as $order): ?>
	<?php echo $order->orderDate.'<br>'?>
	<?php  echo $order->requiredDate.'<br>'?>
	<?php  echo $order->shippedDate.'<br>'?>
	<?php  echo $order->status.'<br>'?>
	<?php  echo $order->comments.'<br>'?>
	<?php  echo $order->customerNumber.'<br><br>'?>
    <?php endforeach; ?>
</body>
</html>